Козачук Дмитрий
urfu-2016/javascript-task-5 pull request #26
Opened 2016-11-08 20:01 UTC by MathDaemon

2016-11-08 20:01 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 9

2016-11-08 21:42 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 9

2016-11-09 07:16 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 9 из 9

2016-11-12 09:40 UTC, savichev-igor reviewed
Чёт мне кажется, что ты немного как говорят "намудрил", попробуй упростить всю логику, а то сейчас читать крайне тяжело =)

Ну и добавляй JSDoc ко всему, чему можно

2016-11-12 09:40 UTC, Savichev-Igor commented on emitter.js
> +            for (var i = 0; i < this.events.length; i++) {
`forEach`

2016-11-12 09:40 UTC, Savichev-Igor commented on emitter.js
> +            for (var i = 0; i < this.events[j].info.length; i++) {
`forEach`

2016-11-12 09:40 UTC, Savichev-Igor commented on emitter.js
> +            for (var i = 0; i < this.events.length; i++) {
`forEach`

2016-11-12 09:40 UTC, Savichev-Igor commented on emitter.js
> +            for (var i = 0; i < info.length; i++) {
`forEach`

2016-11-12 09:40 UTC, Savichev-Igor commented on emitter.js
> +            for (var i = 0; i < sortedEvents.length; i++) {
`forEach`

2016-11-12 09:42 UTC, Savichev-Igor commented
🚀

2016-11-12 15:34 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 9 из 9

2016-11-12 15:54 UTC, savichev-igor reviewed
Пойдёт

2016-11-12 15:54 UTC, Savichev-Igor commented on emitter.js
> +            if (existsEvent === false) {
Зачем такое строгое сравнение, если достаточно просто `if (existsEvent)` =)

2016-11-13 05:48 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 9 из 9

2016-11-14 08:26 UTC, hrundik requested changes
🍅

2016-11-14 08:26 UTC, hrundik commented on emitter.js
> +            this.events.forEach(function (eventsItem) {
У вас события будут работать тем медленнее, чем больше событий обрабатывает ваш `emitter`. Лучше хранить события по-другому.

2016-11-14 08:26 UTC, hrundik commented on emitter.js
> +        offFromOneEvent: function (indexOfEvent, context) {
"приватные" поля в JS стоит как-нибудь обозначать. Обычно для этого используют `_`:`_offFromOneEvent`

2016-11-14 08:26 UTC, hrundik commented on emitter.js
> +                    this.offFromOneEvent(indexOfEvent, context);
В `.offFromOneEvent` имеет смысл передавать сразу `eventsItem`. И тогда `offFromOneEvent` можно вообще сделать методом `eventsItem`.

2016-11-14 08:26 UTC, hrundik commented on emitter.js
> +        emitForOneEvent: function (info) {
И тут та же история: эту функцию имеет смысл унести в сам объект `info`

2016-11-14 08:26 UTC, hrundik commented on emitter.js
> +            sortedEvents = sortedEvents.sort().reverse();
Это будет работать, но очень круто делать сортировку (довольно дорогую операцию) при каждом вызове события. Если не придумывается другого решения, без сортировки, то её лучше делать при добавлении события.

2016-11-14 14:49 UTC, MathDaemon commented on emitter.js
> +            this.events.forEach(function (eventsItem) {
А если убрать сортировку в методе emmit, эта проблема исчезнет?

2016-11-14 16:00 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 9 из 9

2016-11-14 16:05 UTC, MathDaemon commented
Последние 4 замечания учтены. Первое тоже учтено, если проблема была в сортировке.

2016-11-15 06:30 UTC, hrundik requested changes
🍅  Пока не ок

2016-11-15 06:30 UTC, hrundik commented on emitter.js
> +                });
Вынесите создания обработчика в отдельную функцию

2016-11-15 06:30 UTC, hrundik commented on emitter.js
> +                        this.info = savesInfo;
То, что вы делаете, называется `filter`

2016-11-15 06:30 UTC, hrundik commented on emitter.js
> +                if ((name === event) || (event.indexOf(name + '.') === 0)) {
Сравните эту строчку со строчкой `72`. Это одна и та же логика, которую можно вынести в отдельную функцию

2016-11-15 06:30 UTC, hrundik commented on emitter.js
> +            this.events.forEach(function (eventsItem) {
Проблема остаётся, потому что вы всё равно в массиве `events` ищете нужный элемент. А это линейная операция: нужно тем больше операций, чем длиннее массив. Нужно использовать простой hash map (в JS это `Object`) для хранения событий, это структура с константым временем доступа.

2016-11-15 06:30 UTC, hrundik commented on emitter.js
> +            eventsInOrder.reverse().forEach(function (eventsItem) {
Вместо `.reverse()` лучше сразу правильно формировать массив.

2016-11-15 06:30 UTC, hrundik commented on emitter.js
> +                    eventsInOrder[indexEvent] = eventsItem;
Вычисление индекса через `.split('.')` -- очень сурово. Вам это не нужно, достаточно в правильном порядке сформировать список событий, которые нужно обрабатывать.

2016-11-15 15:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-15 15:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-15 16:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-15 17:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-15 18:01 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 9 из 9

2016-11-15 18:36 UTC, MathDaemon commented
Все замечания исправлены.

2016-11-16 14:01 UTC, hrundik requested changes
🍅

2016-11-16 14:01 UTC, hrundik commented on emitter.js
> +var HashMap = require('hashmap');
внешние библиотеки нельзя использовать. Вам хватит простого `Object` (он и есть `hashmap`)

2016-11-16 15:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-16 15:37 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 9 из 9

2016-11-16 15:40 UTC, MathDaemon commented
Заменил hashmap на обычный объект.

2016-11-16 15:45 UTC, hrundik commented on emitter.js
> +                };
Лучше бы вынести создание этого объекта в отдельную функцию. Но на ваших масштабах можно и не делать.

2016-11-16 15:46 UTC, hrundik commented
Пойдёт.

2016-11-16 15:46 UTC, closed without merging