Владислав Барбанягра
urfu-2016/javascript-task-5 pull request #51
Opened 2016-11-09 20:35 UTC by Vladyabra

2016-11-09 20:41 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 9 из 9

2016-11-09 20:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 13 из 13

2016-11-10 13:33 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 13

2016-11-10 14:34 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 13 из 13

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +        callbacks: [],
переменные лучше определять максимально близко к тому месту, где начинаем их использовать. В данном случае наверху

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +                var callback = this.callbacks[i];
можно reduce использовать, тогда не нужно будет это присваивание и будет вроде красивее

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +                    i -= 1;
это тоже будет не нужно

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +                event = event.substr(0, event.lastIndexOf('.'));
плохо, что меняешь сам переданный аргумент. Заведи для этого отдельную переменную

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +            console.info(event);
перед отправкой лучше удалять отладочные элементы))

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +            console.info(event);
код станет чище

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +                var callback = this.callbacks[i];
forEach и это присваивание будет ненужным

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +                callback.handler.apply(callback.context);
3 раза эта строка. Сделай так, чтобы один раз ее написать

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +        doCallback: function (callback) {
зачет тебе возвращать эти функции? Они вспомогательные и не нужны "внешнему миру". Вынеси их отдельно

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +                callback.times = times;
вынеси это в функцию, а то повторение получается

2016-11-12 13:12 UTC, Lakate commented on emitter.js
> +                callback.current = frequency - 1;
в функцию

2016-11-12 13:12 UTC, Lakate commented
🍅

2016-11-16 14:29 UTC, Vladyabra commented on emitter.js
> +                var callback = this.callbacks[i];
Наверное, ты имела в виду `filter`?

2016-11-16 15:03 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 13 из 13

2016-11-18 15:56 UTC, Lakate reviewed
в целом хорошо

2016-11-18 15:56 UTC, Lakate commented on emitter.js
> +            callback = createCallback(event, context, handler);
а почему просто не ```var callback = createCallback(event, context, handler);``` ??

2016-11-18 15:56 UTC, Lakate commented on emitter.js
> +            realApply(curEvent, this.callbacks);
не очень хорошее название функции, непонятно что в ней происходит

2016-11-18 15:56 UTC, Lakate commented on emitter.js
> +                var callback = {};
тоже можно обойтись без этой строки

2016-11-18 15:56 UTC, Lakate commented on emitter.js
> +                var callback = {};
и тут

2016-11-18 15:57 UTC, Lakate commented
дальше с ментором

2016-11-18 15:57 UTC, Lakate commented
🚀

2016-11-21 15:44 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 13 из 13

2016-12-11 09:42 UTC, steppefox requested changes
🍅

2016-12-11 09:42 UTC, steppefox commented on emitter.js
> +    return fullScope.match(new RegExp('^' + scope + '(\\.|$)')) !== null;
Во первых в регулярке ошибка:

```
contains('sliderwut', 'slide.wut') // true
```

Во вторых, намного понятнее выглядело бы:

```
return (fullScope === scope || fullScope.indexOf(scope + '.') === 0)
```

2016-12-11 09:42 UTC, steppefox commented on emitter.js
> +            this.callbacks.push(callback);
Из-за того что структура `callbacks` - это массив, в некоторых местах приходится делать лишние пробеги и проверки. В случае когда у меня два события: `slide1` и `slide2`, и в каждом по 1000 обработчиков, при событии `slide2` будут зря перебираться и проверяться события из `slide1`. Возможно стоит оптимизировать структуру `callbacks`

2016-12-11 12:20 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 13 из 13

2016-12-11 17:20 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 13 из 13

2016-12-13 12:01 UTC, steppefox approved these changes

2016-12-13 12:01 UTC, closed without merging